### PR TITLE
Story

### PR DESCRIPTION
**Pull request by anubiskhan**
@iandouglas @AliSchlereth What would be needed to make stories multiple pages?

Adds stories table.
Adds storyitems table.
Adds relationships.
Adds story index and show views.
Adds spec tests for all.

### CODE REVIEW

**Comment by anubiskhan** [comment]
Would I need to make a pages table and create a one-to-many (story-to-pages) relationship?

**Comment by anubiskhan** [comment]
I'm picturing something like this 
screen shot 2018-04-03 at 7 37 03 pm

**Comment by iandouglas** [comment]
Perhaps for easier scope, so you can focus on other things, you can assign a single monster with a single item and page to a story, and put all that data in the Stories table for now. Once you get the core functionality working then perhaps consider "normalizing" that data into separate tables one at a time.

**Comment by anubiskhan** [comment]
I have the underlying structure built already, other than the pages table. but I will just leave it as a story is just its own description for now and work on finishing the actual website part of it

**Pull request merged**
